name: Deployment
on:
  push:
    branches: [ prod ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd derum/
            git pull
            cd backend/
            npm install
            rm -rf dist/
            npm run build
            npm run typeorm migration:run
            pm2 restart derum
            cd ..
            cd frontend/
            npm install
            npm run build
            pm2 restart client

